version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
    links:
      - golang
  golang:
    image: golang:1.12.4-stretch
    container_name: golang
    hostname: golang
    volumes:
      - "./:/src"
    working_dir: /src
    command: [sh, -c, go get github.com/labstack/echo && go run main.go]
    ports:
      - "8080:8080"
    links:
      - mysql
  mysql:
    image: mysql:5.7
    hostname: mysql
    volumes:
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=database"
